services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: pitlaneshop-sqlserver
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'PitLaneShop@Dev2024'
    ports:
      - '1433:1433'
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: unless-stopped

  backend:
    image: ghcr.io/vinicius-je/xp-educacao-desf5@sha256:d5975ab728a3c3f9cdd7baeff412d0b4b15399d0b9659cdc5e8ba5559d111bbe
    container_name: pitlaneshop-backend
    depends_on:
      - sqlserver
    ports:
      - '3000:8080'
      - '3001:8081'
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=PitLaneShop;User Id=sa;Password=PitLaneShop@Dev2024;TrustServerCertificate=True;MultipleActiveResultSets=true"
    restart: unless-stopped

  frontend:
    image: ghcr.io/vinicius-je/xp-educacao-desf5-frontend@sha256:ee0f5ecf76babeeaee42801eee177bf3c432279274b0fbe8d914a27766b1655d
    container_name: pitlaneshop-frontend
    ports:
      - '4000:4000'
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  sqlserver_data:
